### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by sbratakonda** [MrExplode/ltc4j#3]
Hi, this is not an issue, but kinda request. i am kinda running into issues with the frames in millisec that i am generating from a Laptop internal time. The frames are not coming as expected.
ex: 13:04:12:xx --> here he xx as frames in millisec.

Requesting for a an example of continious time code generation from an internal time with frames

Ex: [](https://allensarkisyan.github.io/VideoFrameDocs/)
![Untitled](https://user-images.githubusercontent.com/65026173/81417551-fc13be00-9168-11ea-9c84-42b5e7b654f6.png)

**Comment by MrExplode** [comment]
I assume this is not related to my library, right?

In the readme I already wrote a simple continuous timecode calculation, but here you go:
```java
long start = 0;
long time = 0;
int framerate = ... // your framerate
while (System.currentTimeMillis() >= time + (1000 / framerate) {
    time = System.currentTimeMillis();
    long elapsed = time - start;
    long var = elapsed;
    int hour = (int) (var / 60 / 60 / 1000);
    var = var - (hour * 60 * 60 * 1000);
    int min = (int) (var / 60 / 1000);
    var = value - (min * 60 * 1000);
    int sec = (int) (var / 1000);
    var = value - (sec * 1000);
    int frame = (int) (var / (1000 / framerate));
    // work with time values
    //do whatever you want, eg. send it out
}
```

I threw away the idea to count the elapsed frames, because if you using any framerate other than 25, you will get miscalculations due fractions. (eg. 1000 / 24 not a whole number)

**Comment by sbratakonda** [comment]
Hey There, I have seen that, and i did felt the same, but is there anyother way to do it ?
check this out [https://allensarkisyan.github.io/VideoFrameDocs/](https://allensarkisyan.github.io/VideoFrameDocs/)

**Comment by MrExplode** [comment]
I don't know. Why would you want to count frames?

**Comment by sbratakonda** [comment]
I am actually building a Clapper Slate that display current time with
frames as master clock and with that generated time i then will jam sync
the camera that I have with LTC time code signal

**Comment by aillience** [comment]
Hello, I use LTCPacket like this
`LTCPacket packet = new LTCPacket(0,1,2,20,Framerate.FRAMERATE_25);
        byte[] data = packet.asByteArray();`.
but when I print data,The array is [0,0,.....0].Why?
